utils/src/main/docker/Dockerfile
=> Fixes issue #7 - Switch the utils image to use oraclelinux:7-slim from alpine

functional-tests/src/docker/Artifacts.Dockerfile
=> Fixes issue #12 - Switch test images to use oraclelinux:7-slim from alpine

operator/src/main/helm/coherence-operator/Chart.yaml, operator/src/main/helm/coherence/Chart.yaml
modified:   operator/src/main/helm/coherence-operator/Chart.yaml
modified:   operator/src/main/helm/coherence/Chart.yaml
=> #4 chart metadata add keywords

functional-tests/pom.xml, operator/pom.xml, pom.xml, utils/pom.xml
Update master to have coherence-operator version 1.1.0-SNAPSHOT
=> Update coherence-operator version to 1.1.0-SNAPSHOT

operator/src/main/helm/coherence-operator/templates/deployment.yaml, operator/src/main/helm/coherence-operator/values.yaml
Fix Custom elasticsearchEndpoint host and port and not being passed to fluentd #60
=> Fix Custom elasticsearchEndpoint host and port and not being passed

README.md
README.md
* Change formerly internal links to point to gh-pages.
* Put Slack link at top as requested by Aleks, JK, and Patrick.
=> #31 Move docs to gh-pages

docs/quickstart.md, docs/user-guide.md
=> #31 Apply @jfialli suggestions.

docs/logcapture.md, docs/prometheusoperator.md, docs/user-guide.md
modified:   docs/logcapture.md
modified:   docs/prometheusoperator.md
modified:   docs/user-guide.md
- Reference samples in context.
=> #31 Reference samples in context

docs/user-guide.md
=> #123 Document "one at a time" scaling.

utils/src/main/docker/init.sh
Cherry pick from 1.0 -> master
=> fix directory permissions in init.sh script (#131)

operator/src/main/helm/coherence/scripts/startCoherence.sh, pom.xml
Update to latest coherence docker image version with coherence-metrics/coherence-management modules replacing coherence-rest.
=> Update to coherence version with metrics mgmt reorg

operator/src/main/helm/coherence/values.yaml
#123 Change Coherence podManagementPolicy to Parallel per JK. (#129)
=> Cherry pick the following change from 1.0-> master

docs/logcapture.md, docs/prometheusoperator.md
Also minor edits in Log Capture
=> First Pass of the Prometheus doc

docs/samples/operator/logging/custom-logs/README.md, docs/samples/operator/logging/log-capture/README.md, docs/samples/operator/logging/own-elasticsearch/README.md, docs/samples/operator/metrics/enable-metrics/README.md, docs/samples/operator/metrics/own-prometheus/README.md, docs/samples/operator/metrics/ssl/README.md
=> Updated configre custom logger sample

docker-hub-readme.md
Made this file consistent with the other README files.
=> Updated docker hub readme

pom.xml
See https://github.com/oracle/coherence-operator/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
See https://github.com/oracle/coherence-operator/issues/286
=> Fix jackson-databind vulnerabilities found in pom.xml

pom.xml
Use Coherence 12.2.1.4 GA artifacts
=> 12.2.1.4 release

docs-unstable/2.0.0-1910211023/main/config.js, docs-unstable/2.0.0-alpha1/main/config.js, docs-unstable/2.0.0-alpha2/main/config.js, docs-unstable/2.0.0-graal1/main/config.js, docs/1.0.0/index.md, docs/2.0.0/main/config.js, index.md
=> Update Slack links

Makefile, deploy/crds/coherence.oracle.com_coherenceclusters_crd.yaml, deploy/crds/coherence.oracle.com_coherenceinternals_crd.yaml, deploy/crds/coherence.oracle.com_coherenceroles_crd.yaml, docs/clusters/020_k8s_resources.adoc, pkg/apis/coherence/v1/coherencecluster_types.go, pkg/apis/coherence/v1/coherencerole_types.go, pkg/controller/coherencecluster/coherencecluster_controller.go
Add short names to the Coherence CRDs
=> Add short names to the Coherence CRDs

.github/workflows/k8s-matrix.yaml, Makefile, docs/about/04_coherence_spec.adoc, java/coherence-utils/pom.xml, java/coherence-utils/src/main/java/com/oracle/coherence/k8s/Main.java, java/coherence-utils/src/main/java/com/oracle/coherence/k8s/OperatorRestServer.java, java/coherence-utils/src/test/java/com/oracle/coherence/k8s/OperatorRestServerIT.java, java/operator-test-spring/pom.xml, java/operator-test/pom.xml, java/pom.xml
Change Coherence dependencies to CE 20.12
=> Coherence 20 12

dashboards/grafana/cache-details-dashboard.json, dashboards/grafana/caches-summary-dashboard.json, dashboards/grafana/coherence-dashboard-main.json, dashboards/grafana/elastic-data-summary-dashboard.json, dashboards/grafana/federation-details-dashboard.json, dashboards/grafana/federation-summary-dashboard.json, dashboards/grafana/http-servers-summary-dashboard.json, dashboards/grafana/kubernetes-summary-dashboard.json, dashboards/grafana/machines-summary-dashboard.json, dashboards/grafana/member-details-dashboard.json, dashboards/grafana/members-summary-dashboard.json, dashboards/grafana/persistence-summary-dashboard.json, dashboards/grafana/proxy-server-detail-dashboard.json, dashboards/grafana/proxy-servers-summary-dashboard.json, dashboards/grafana/service-details-dashboard.json, dashboards/grafana/services-summary-dashboard.json
=> Check Grafana Dashboards to ensure Cluster or service name with $ work

java/pom.xml
- Update Spring Boot version to `2.6.7`
resolves #529
=> Operator should test with a newer Spring Boot version

docs/metrics/030_importing.adoc, docs/metrics/040_dashboards.adoc
Signed-off-by: Tim Middleton <tim.middleton@oracle.com>
=> Update docs to specify recommended Grafana versions

test/coherence_compatibility/certifiy_deployment_test.go
Signed-off-by: Tim Middleton <tim.middleton@oracle.com>
=> Ensure certification tests use imagePullSecrets from environment

dashboards/grafana/executor-details.json, dashboards/grafana/executors-summary.json, dashboards/grafana/grpc-proxy-details-dashboard.json, dashboards/grafana/grpc-proxy-summary-dashboard.json, docs/management/025_coherence_cli.adoc
Coh 28724 - Add gRPC Proxy Summary Dashboard
=> Coh 28724 - Add gRPC Proxy Summary Dashboard

Dockerfile, Makefile, config/crd/kustomization.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manager/service.yaml, config/manifests/bases/coherence-operator.clusterserviceversion.yaml, docs/about/03_quickstart.adoc, docs/installation/01_installation.adoc, docs/installation/07_webhooks.adoc, docs/installation/09_RBAC.adoc, docs/metrics/020_metrics.adoc, docs/networking/020_dual_stack.adoc, docs/other/041_global_labels.adoc, examples/015_simple_image/README.adoc, examples/095_network_policies/manifests/net-test-client.yaml, examples/095_network_policies/manifests/net-test-coherence-server.yaml, examples/095_network_policies/manifests/net-test-coherence.yaml, examples/095_network_policies/manifests/net-test-operator-server.yaml, examples/095_network_policies/manifests/net-test-operator.yaml, examples/095_network_policies/manifests/net-test-webhook.yaml, examples/300_helm/chart/values.yaml, examples/400_Istio/README.adoc, examples/no-operator/04_istio/Dockerfile, examples/no-operator/04_istio/README.adoc, hack/next-version.sh, helm-charts/coherence-operator/templates/deployment.yaml, java/pom.xml
=> Update version to 3.4.2
